config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :questions

  get 'show' => 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :text, presence: true
  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true # Проверка заполненности
  validates :email, :username, uniqueness: true # Проверка уникальности
  validates :email, email: true # Проверка формата email
  validates :username, length: { maximum: 40 } # Проверка длины nickname
  validates :username, format: /\A\w+\z/ # Проверка формата nickname

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_validation :username_to_lowercase
  before_save :encrypt

  def encrypt
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  # Перевод nickname в нижний регистр
  def username_to_lowercase
    if self.username.present?
      self.username.downcase!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = [
      User.new(
        id: 1,
        name: 'Sergey',
        username: 'ncsergey',
        avatar_url: 'https://s.gravatar.com/avatar/258f9cd3d96f4d5c5acf0ddcde660e92?s=80'
      ),
      User.new(
        id: 2,
        name: 'Max',
        username: 'titan'
      )
    ]
  end

  def new
  end

  def edit
  end

  def show
    @user = User.new(
      name: 'Sergey',
      username: 'ncsergey',
      avatar_url: 'https://s.gravatar.com/avatar/258f9cd3d96f4d5c5acf0ddcde660e92?s=80'
    )

    @questions = [
        Question.new(text: "Как дела?", created_at: Date.parse("10.09.2017")),
        Question.new(text: "Что делаешь?", created_at: Date.parse("10.09.2017"))
    ]

    @new_question = Question.new

    @questions_count = @questions.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path "avatar.jpg"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Вопросы</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <div class="header-logo">
        <div class="container">
          <h1 class="header-title"><%= link_to "Вопросы", root_path %></h1>
        </div>
      </div>
    </div>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= question.created_at.strftime("%d %b %M:%H") %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%#= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <h1 class="title-small"><%= @questions_count %></h1>
    <p><%= Russian.p(@questions_count, "вопрос", "вопроса", "вопросов") %></p>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>